sentence_pairs = [
    ("The dog ran to the tree.", "Der Hund rannte zum Baum."),
    ("I want to eat good food.", "Ich möchte gutes Essen essen."),
    ("The cat played with the mouse.", "Die Katze spielte mit der Maus."),
    ("We saw a bear in the forest.", "Wir sahen einen Bären im Wald."),
    ("The boy laughed at the funny story.", "Der Junge lachte über die lustige Geschichte."),
    ("She found a red book on the bed.", "Sie fand ein rotes Buch auf dem Bett."),
    ("The bird flew over the green garden.", "Der Vogel flog über den grünen Garten."),
    ("He stopped to look at the blue sky.", "Er hielt an, um den blauen Himmel zu betrachten."),
    ("The fish swam in the cold river.", "Der Fisch schwamm im kalten Fluss."),
    ("They walked through the dark forest.", "Sie gingen durch den dunklen Wald."),
    ("I will take my dog for a walk.", "Ich werde mit meinem Hund spazieren gehen."),
    ("She has a beautiful garden at home.", "Sie hat einen schönen Garten zu Hause."),
    ("Can you help me with my homework?", "Kannst du mir bei meinen Hausaufgaben helfen?"),
    ("The children are playing in the park.", "Die Kinder spielen im Park."),
    ("I found my keys under the table.", "Ich fand meine Schlüssel unter dem Tisch."),
    ("He is reading a book about magic.", "Er liest ein Buch über Magie."),
    ("We will go to the beach tomorrow.", "Wir werden morgen zum Strand gehen."),
    ("She loves to dance in the rain.", "Sie liebt es, im Regen zu tanzen."),
    ("They are watching a movie tonight.", "Sie sehen sich heute Abend einen Film an."),
    ("I need to buy some new clothes.", "Ich muss einige neue Kleider kaufen."),
    ("The sun is shining brightly today.", "Die Sonne scheint heute hell."),
    ("He has a big smile on his face.", "Er hat ein großes Lächeln im Gesicht."),
    ("She enjoys reading stories before bed.", "Sie liest gerne Geschichten vor dem Schlafengehen."),
    ("We will visit our grandparents this weekend.", "Wir werden unsere Großeltern am Wochenende besuchen."),
    ("The flowers are blooming in spring.", "Die Blumen blühen im Frühling."),
    ("I like to drink tea in the morning.", "Ich trinke gerne Tee am Morgen."),
    ("He plays soccer every Saturday afternoon.", "Er spielt jeden Samstagnachmittag Fußball."),
    ("The baby is sleeping in her crib.", "Das Baby schläft in ihrem Bettchen."),
    ("They have a picnic by the lake.", "Sie haben ein Picknick am See."),
    ("She is painting a picture of a mountain.", "Sie malt ein Bild von einem Berg."),
    ("I saw a fox running across the field.", "Ich sah einen Fuchs über das Feld laufen."),
    ("He likes to ride his bike after school.", "Er fährt nach der Schule gerne mit seinem Fahrrad."),
    ("We are going to have a party next week.", "Wir werden nächste Woche eine Party haben."),
    ("The stars are shining in the night sky.", "Die Sterne leuchten am Nachthimmel."),
    ("She baked cookies for her friends.", "Sie backte Kekse für ihre Freunde."),
    ("He found an old coin in the garden.", "Er fand eine alte Münze im Garten."),
    ("They are playing cards at the table.", "Sie spielen Karten am Tisch."),
    ("I want to learn how to play guitar.", "Ich möchte lernen, wie man Gitarre spielt."),
    ("The train arrived at the station on time.", "Der Zug kam pünktlich am Bahnhof an."),
    ("She wore a beautiful dress to the party.", "Sie trug ein schönes Kleid zur Party."),
    ("We saw many birds flying south for winter.", "Wir sahen viele Vögel nach Süden fliegen für den Winter."),
    ("He took his dog for a walk in the evening.", "Er ging abends mit seinem Hund spazieren."),
    ("I will call you later this afternoon.", "Ich werde dich später am Nachmittag anrufen."),
    ("They built a sandcastle on the beach."," Sie bauten eine Sandburg am Strand."), 
    ("She loves to swim in the ocean."," Sie liebt es, im Ozean zu schwimmen."), 
    ("He has many friends at school."," Er hat viele Freunde in der Schule."), 
    ("We went hiking in the mountains last weekend."," Wir sind letztes Wochenende in den Bergen wandern gegangen."), 
    ("The children played games outside all day."," Die Kinder spielten den ganzen Tag draußen Spiele."), 
    ("I bought some apples and oranges at the store."," Ich kaufte Äpfel und Orangen im Laden."), 
    ("She enjoys listening to music while studying."," Sie hört gerne Musik während des Studierens."), 
    ("They visited a museum during their trip."," Sie besuchten ein Museum während ihrer Reise."), 
    ("He wrote a letter to his pen pal."," Er schrieb einen Brief an seinen Brieffreund."), 
    ("We had fun playing board games together."," Wir hatten Spaß beim Spielen von Brettspielen zusammen."), 
    ("The sky turned dark before it started raining."," Der Himmel wurde dunkel, bevor es zu regnen begann."), 
    ("She made a cake for her friend's birthday."," Sie machte einen Kuchen zum Geburtstag ihrer Freundin."), 
    ("He likes to draw pictures of animals."," Er zeichnet gerne Bilder von Tieren."), 
    ("We watched fireworks on New Year's Eve."," Wir sahen Feuerwerke an Silvester."), 
    ("The library has many interesting books."," Die Bibliothek hat viele interessante Bücher."), 
    ("I enjoy taking long walks in nature."," Ich genieße es, lange Spaziergänge in der Natur zu machen."), 
    ("They celebrated their anniversary with dinner out."," Sie feierten ihren Jahrestag mit einem Abendessen draußen."), 
    ("She feels happy when she helps others."," Sie fühlt sich glücklich, wenn sie anderen hilft."), 
    ("He always finds time to read before bed."," Er findet immer Zeit, vor dem Schlafengehen zu lesen."), 
    ("We learned about different cultures in class."," Wir lernten über verschiedene Kulturen im Unterricht."), 
    ("The dog barked loudly when strangers arrived."," Der Hund bellte laut, als Fremde ankamen."), 
    ("She took beautiful photos during her vacation."," Sie machte wunderschöne Fotos während ihres Urlaubs."), 
    ("They enjoyed watching movies together on weekends."," Sie genossen es, am Wochenende zusammen Filme zu schauen."), 
    ("He fixed his bike after it broke down."," Er reparierte sein Fahrrad, nachdem es kaputt gegangen war."), 
    ("We planted flowers in our garden last spring."," Wir pflanzten Blumen in unserem Garten letzten Frühling."), 
    ("She likes to collect stamps from different countries."," Sie sammelt gerne Briefmarken aus verschiedenen Ländern."), 
    ("He plays basketball every Friday evening."," Er spielt jeden Freitagabend Basketball."), 
    ("We had a barbecue party last summer."," Wir hatten letzten Sommer eine Grillparty."), 
    ("The teacher explained the lesson clearly."," Der Lehrer erklärte die Lektion klar und deutlich."), 
    ("I found my favorite shirt at the store yesterday."," Ich fand mein Lieblingshemd gestern im Laden."), 
    ("They went camping in the woods last weekend."," Sie gingen letztes Wochenende campen im Wald."), 
    ("She enjoys painting landscapes and portraits."," Sie malt gerne Landschaften und Porträts."), 
    ("He always helps his neighbors with their chores."," Er hilft immer seinen Nachbarn bei ihren Aufgaben."), 
    ("We visited our relatives during the holidays."," Wir besuchten unsere Verwandten während der Feiertage."), 
    ("The children played soccer until sunset."," Die Kinder spielten Fußball bis zum Sonnenuntergang."), 
    ("She baked cookies for her classmates' party."," Sie backte Kekse für die Party ihrer Klassenkameraden."), 
    ("He enjoys fishing by the lake on weekends."," Er angelt gerne am See an den Wochenenden."), 
    ("We watched documentaries about nature and wildlife."," Wir sahen Dokumentationen über die Natur und Wildtiere.") ,  
      ('I like to drink coffee every morning.', 'Ich trinke jeden Morgen gerne Kaffee.'),
      ('The children are excited about their trip.', 'Die Kinder sind aufgeregt wegen ihrer Reise.'),
      ('She enjoys reading books before going to sleep.', 'Sie liest gerne Bücher, bevor sie schlafen geht.'),
      ('He plays video games with his friends online.', 'Er spielt online Videospiele mit seinen Freunden.'),
      ('We often go hiking during our vacations.', 'Wir gehen oft wandern während unserer Ferien.'),
      ('The cat sleeps on the windowsill every day.', 'Die Katze schläft jeden Tag auf der Fensterbank.'),
      ('They love watching cartoons on Saturday mornings.', 'Sie lieben es, samstags morgens Cartoons zu schauen.'),
      ('I found an interesting article online yesterday.', 'Ich fand gestern einen interessanten Artikel online.'),
      ('She is learning how to play piano this year.', 'Sie lernt dieses Jahr, wie man Klavier spielt.'),
      ('We had fun playing games at the party.', 'Wir hatten Spaß beim Spielen von Spielen auf der Party.'),
      ('The sun sets beautifully over the mountains.', 'Die Sonne geht schön über den Bergen unter.'),
      ('He enjoys cooking new recipes for dinner.', 'Er kocht gerne neue Rezepte zum Abendessen.'),
      ('They went for a walk along the riverbank.', 'Sie gingen am Ufer des Flusses spazieren.'),
      ('I want to travel around Europe next summer.', 'Ich möchte nächsten Sommer durch Europa reisen.'),
      ('She loves taking photographs of nature.', 'Sie liebt es, Fotos von der Natur zu machen.'),
      ('He often visits his grandparents on weekends.', 'Er besucht oft seine Großeltern am Wochenende.'),
      ('We built a snowman during winter vacation.', 'Wir bauten einen Schneemann während der Winterferien.'),
      ('The flowers bloom beautifully in spring.', 'Die Blumen blühen schön im Frühling.'),
      ('I enjoy listening to music while studying.', 'Ich höre gerne Musik beim Lernen.'),
      ('They celebrated their victory with a party.', 'Sie feierten ihren Sieg mit einer Party.')]

print(len(sentence_pairs))
word_pairs = [
    ('water', 'Wasser'),
    ('away', 'weg'),
    ('good', 'gut'),
    ('want', 'wollen'),
    ('over', 'über'),
    ('how', 'wie'),
    ('did', 'tat'),
    ('man', 'Mann'),
    ('going', 'gehen'),
    ('where', 'wo'),
    ('would', 'würde'),
    ('or', 'oder'),
    ('took', 'nahm'),
    ('school', 'Schule'),
    ('think', 'denken'),
    ('home', 'Zuhause'),
    ('who', 'wer'),
    ('didn', 'nicht'),  # "didn't" is often translated as "nicht"
    ('ran', 'rannte'),
    ('know', 'wissen'),
    ('bear', 'Bär'),  # Can also mean "tragen" in different contexts
    ('can', 'können'),
    ('again', 'wieder'),
    ('cat', 'Katze'),
    ('long', 'lang'),
    ('things', 'Dinge'),
    ('new', 'neu'),
    ('after', 'nach'),
    ('wanted', 'wollte'),
    ('eat', 'essen'),
    ('everyone', 'jeder'),  # Can also mean "alle"
    ('our', 'unser'),
    ('two', 'zwei'),
    ('has', 'hat'),
    ('yes', 'ja'),
    ('play', 'spielen'),
    ('take', 'nehmen'),
    ('thought', 'Gedanke'),  # Can also mean "dachte" (past tense of think)
    ('dog', 'Hund'),
    ('well', 'gut'),  # Can also mean "brunnen" in different contexts
    ('find', 'finden'),
    ('more', 'mehr'),
    ('I', 'ich'),
    ("ll", "werde"),  # Short for "will" in future tense
    ("round", "rund"),
    ("tree", "Baum"),
    ("magic", "Magie"),
    ("shouted", "rief"),
    ("us", "uns"),
    ("other", "anderer"),
    ("food", "Essen"),
    ("fox", "Fuchs"),
    ("through", "durch"),
    ("way", "Weg"),
    ("been", "gewesen"),
    ("stop", "stoppen"),
    ("must", "müssen"),
    ("red", "rot"),
    ("door", "Tür"),
    ("right", "rechts"),  # Can also mean "richtig"
    ("sea", "Meer"),
    ("these", "diese"),
    ("began", "begann"),
    ("boy", "Junge"),
    ("animals", "Tiere"),
    ("never", "nie"),
    ("next", "nächster"),
    ("first", "erste"),
    ("work", "Arbeit"),  # Can also mean "arbeiten" (to work)
    ("lots", "viele"),  # Can also mean 'eine Menge'
    ("need", "brauchen"),
   ("that", "dass"), 
   ("baby", "Baby"), 
   ("fish", "Fisch"), 
   ("gave", "gab"), 
   ("mouse", "Maus"), 
   ("something", "etwas"), 
   ("bed", "Bett"), 
   ("may", "dürfen"), 
   ("still", "noch"), 
   ("found", "fand"), 
   ("live", "leben"), 
   ("say", "sagen"), 
   ("soon", "bald"), 
   ("night", "Nacht"), 
   ("narrator", "Erzähler"), 
   ("small", "klein"), 
   ("car", "Auto"), 
   ("couldn", 'konnte nicht'),  
   ('t', 't'),  
   ('three', 'drei'),  
   ('head', 'Kopf'),  
   ('king', 'König'),  
   ('town', 'Stadt'),  
   ('I', 'ich'),  
   ('ve', 'habe'),  
   ('around', 'herum'),  
   ('every', 'jeder'),  
   ('garden', 'Garten'),  
   ('fast', 'schnell'),  
   ('only', 'nur'),  
   ('many', 'viele'),  
   ('laughed', 'lachte'),  
   ('let', 'lassen'),  
   ('much', 'viel'),  
   ('suddenly', 'plötzlich'),  
   ('told', 'sagte'),  
   ('another', 'ein anderer'),  
   ('great', 'großartig'),  
   ('why', 'warum'),  
  ('cried', 'schrie'),
  ('keep', 'behalten'),
  ('room', 'Zimmer'),
  ('last', 'letzte'),
  ('jumped', 'sprang'),
  ('because', 'weil'),
  ('even', 'sogar'),
  ('am', 'bin'),
  ('before', 'vor'),
  ('gran', 'Oma'),
  ('clothes', 'Kleidung'),
  ('tell', 'erzählen'),
  ('key', 'Schlüssel'),
  ('fun', 'Spaß'),
  ('place', 'Platz'),
  ('mother', 'Mutter'),
  ('sat', 'saß'),
  ('boat', 'Boot'),
  ('window', 'Fenster'),
  ('sleep', 'schlafen'),
  ('feet', 'Füße'),
("morning","morgen"),
("queen","Königin"),
("each","jeder"),
("book","Buch"),
("its","sein"),
("green","grün"),
("different","anders"),
("let","lassen"),
("girl","Mädchen"),
("which","welches"),
("inside","drinnen"),
("run","laufen"),
("any","irgendwelche"),
("under","unter"),
("hat","Hut"),
("snow","Schnee"),
("air","Luft"),
("trees","Bäume"),
("bad","schlecht"),
("tea","Tee"),
("top","oben"),
("eyes","Augen"),
("fell","fiel"),
("friends","Freunde"),
("box","Kiste"),
("dark","dunkel"),
("grandad","Opa"),
("there","da"),
("looking","schauend"),
("end","Ende"),
("than","als"),
("best","beste"),
("better","besser"),
("hot","heiß"),
("sun","Sonne"),
("across","über"),
("gone","weg"),
("hard","hart"),
("floppy","schlaff"),
("really","wirklich"),
("wind","Wind"),
("wish","Wunsch"),
("eggs","Eier"),
("once","einmal"),
("please","bitte"),
("thing","Ding"),
("stopped","hörte auf"),
("ever","jemals"),
("miss","verpassen"),
("most","meistens"),
("cold","kalt"),
("park","Park"),
("lived","lebte"),
("birds","Vögel"),
("duck","Ente"),
("horse","Pferd"),
("rabbit","Kaninchen"),
("white","weiß"),   
('coming','kommen'),    
('he','er'),    
('s','s'),    
('river','Fluss'),    
('liked','mochte'),    
('giant','Riese'),    
('looks','Aussehen'),    
('use','benutzen'),    
('along','entlang'),    
('plants','Pflanzen'),    
('dragon','Drache'),    
('pulled','zog'),    
('we','wir'),    
('re','sind'),    
('fly','fliegen'),    
('grow','wachsen'),    
('make','machen')
]

sentence_pairs_1 = [
    ("I am a good person.", "Ich bin ein guter Mensch."),
    ("You are a great man.", "Du bist ein großartiger Mann."),
    ("He is a new person.", "Er ist eine neue Person."),
    ("She has a long way to go.", "Sie hat einen langen Weg vor sich."),
    ("It is a good day.", "Es ist ein guter Tag."),
    
    ("We have a great time.", "Wir haben eine großartige Zeit."),
    ("They do a good job.", "Sie machen einen guten Job."),
    ("I say it is good.", "Ich sage, es ist gut."),
    ("You get a new thing.", "Du bekommst eine neue Sache."),
    ("He makes a good plan.", "Er macht einen guten Plan."),

    ("She goes to the park.", "Sie geht zum Park."),
    ("It is a long year.", "Es ist ein langes Jahr."),
    ("We do it every day.", "Wir machen es jeden Tag."),
    ("They have a little time.", "Sie haben wenig Zeit."),
    ("I want to go home.", "Ich möchte nach Hause gehen."),

    ("You have a good idea.", "Du hast eine gute Idee."),
    ("He is a great man.", "Er ist ein großartiger Mann."),
    ("She has a new plan.", "Sie hat einen neuen Plan."),
    ("It is a good thing.", "Es ist eine gute Sache."),
    ("We say it is great.", "Wir sagen, es ist großartig."),

    ("They get a new year.", "Sie bekommen ein neues Jahr."),
    ("I make a good choice.", "Ich treffe eine gute Wahl."),
    ("You are a good friend.", "Du bist ein guter Freund."),
    ("He has a long way to go.", "Er hat einen langen Weg vor sich."),
    ("She does a great job.", "Sie macht einen großartigen Job."),

    # Continuing with more sentences:
    
    ('It is a new day.', 'Es ist ein neuer Tag.'), 
    ('We have a long time.', 'Wir haben viel Zeit.'), 
    ('They say it is good.', 'Sie sagen, es ist gut.'), 
    ('I get a new job.', 'Ich bekomme einen neuen Job.'), 
    ('You make a good plan.', 'Du machst einen guten Plan.'), 
   
   ('He goes to the store.', 'Er geht zum Laden.'), 
   ('She is a good friend.', 'Sie ist eine gute Freundin.'), 
   ('It is a great year.', 'Es ist ein großartiges Jahr.'), 
   ('We do it the right way.', 'Wir machen es auf die richtige Weise.'), 
   ('They have little time.', 'Sie haben wenig Zeit.'), 
   
   ('I want to be great.', 'Ich möchte großartig sein.'), 
   ('You are a new person.', 'Du bist eine neue Person.'), 
   ('He has a good idea.', 'Er hat eine gute Idee.'), 
   ('She makes a great choice.', 'Sie trifft eine großartige Wahl.'), 
   ('It is a long way.', 'Es ist ein weiter Weg.'), 

   ('We say it is new.', 'Wir sagen, es ist neu.'), 
   ('They get a good time.', 'Sie haben eine gute Zeit.'), 
   ('I do it every year.', 'Ich mache es jedes Jahr.'), 
   ('You have a great plan.', 'Du hast einen großartigen Plan.'), 
   ('He is a little man.', 'Er ist ein kleiner Mann.'), 

   ('She goes the long way.', 'Sie geht den langen Weg.'), 
   ('It is a good year.', 'Es ist ein gutes Jahr.'), 
   ('We make a new plan.', 'Wir machen einen neuen Plan.'), 
   ('They say it is great.', 'Sie sagen, es ist großartig.'), 
   ('I want to have fun.', 'Ich möchte Spaß haben.'),

   # Final sentences:
   ('You are my best friend.', 'Du bist mein bester Freund.'), 
   ('He will be here soon.', 'Er wird bald hier sein.'), 
   ('She can make it happen.', 'Sie kann es möglich machen.'), 
   ('It feels like the first day of summer.', 'Es fühlt sich an wie der erste Sommertag.')]
sentence_pairs = [
    ("be good", "sei gut"),
    ("be a person", "sei eine Person"),
    ("be the first", "sei der Erste"),
    ("have a good time", "habe eine gute Zeit"),
    ("have a great year", "habe ein großartiges Jahr"),
    ("do it", "mach es"),
    ("do a great thing", "mache eine großartige Sache"),
    ("say it", "sag es"),
    ("say a new thing", "sage eine neue Sache"),
    ("get the thing", "hole die Sache"),
    ("get a new way", "bekomme einen neuen Weg"),
    ("make it", "mache es"),
    ("make a long day", "mache einen langen Tag"),
    ("go the way", "gehe den Weg"),
    ("go a little time", "gehe eine kurze Zeit"),
    ("time is long", "die Zeit ist lang"),
    ("time is a great thing", "die Zeit ist eine großartige Sache"),
    ("person is good", "die Person ist gut"),
    ("person is a man", "die Person ist ein Mann"),
    ("year is long", "das Jahr ist lang"),
    ("year is the first", "das Jahr ist das erste"),
    ("way is great", "der Weg ist großartig"),
    ("way is a little long", "der Weg ist ein wenig lang"),
    ("day is good", "der Tag ist gut"),
    ("day is the last", "der Tag ist der letzte"),
    ("thing is new", "die Sache ist neu"),
    ("thing is good", "die Sache ist gut"),
    ("man is good", "der Mann ist gut"),
    ("man is a person", "der Mann ist eine Person"),
    ("i am good", "ich bin gut"),
    ("i have time", "ich habe Zeit"),
    ("i say it", "ich sage es"),
    ("i do a great thing", "ich mache eine großartige Sache"),
    ("you are good", "du bist gut"),
    ("you have a long way", "du hast einen langen Weg"),
    ("you get it", "du bekommst es"),
    ("he is a great man", "er ist ein großartiger Mann"),
    ("he does a little thing", "er macht eine kleine Sache"),
    ("she is good", "sie ist gut"),
    ("she makes it", "sie macht es"),
    ("it is great", "es ist großartig"),
    ("it is the first day", "es ist der erste Tag"),
    ("we are good", "wir sind gut"),
    ("we have a little time", "wir haben wenig Zeit"),
    ("we go a great way", "wir gehen einen großartigen Weg"),
    ("they are good", "sie sind gut"),
    ("they do a new thing", "sie machen eine neue Sache"),
    ("the way is long", "der Weg ist lang"),
    ("the year is good", "das Jahr ist gut"),
    ("the person is great", "die Person ist großartig"),
    ("a great day", "ein großartiger Tag"),
    ("a little thing", "eine kleine Sache"),
    ("an old way", "ein alter Weg"),
    ("an important person", "eine wichtige Person"),
    ("good time", "gute Zeit"),
    ("good day", "guter Tag"),
    ("first year", "erstes Jahr"),
    ("first man", "erster Mann"),
    ("last thing", "letzte Sache"),
    ("last way", "letzter Weg"),
    ("long day", "langer Tag"),
    ("long time", "lange Zeit"),
    ("great man", "großartiger Mann"),
    ("great thing", "großartige Sache"),
    ("little day", "kleiner Tag"),
    ("little time", "kurze Zeit"),
    ("a good thing", "eine gute Sache"),
    ("an important day", "ein wichtiger Tag"),
    ("new way", "neuer Weg"),
    ("new person", "neue Person"),
    ("it is good", "es ist gut"),
    ("she is great", "sie ist großartig"),
    ("he has time", "er hat Zeit"),
    ("they have a way", "sie haben einen Weg"),
    ("we make it", "wir machen es"),
    ("i get it", "ich bekomme es"),
    ("you do it", "du machst es"),
    ("time is great", "die Zeit ist großartig"),
    ("day is the first", "der Tag ist der erste"),
    ("person is the last", "die Person ist die letzte"),
    ("the year is new", "das Jahr ist neu"),
    ("the thing is long", "die Sache ist lang"),
    ("a good man", "ein guter Mann"),
    ("an old day", "ein alter Tag"),
    ("new year", "neues Jahr"),
    ("good person", "gute Person"),
    ("great day", "großartiger Tag"),
    ("little thing", "kleine Sache"),
    ("first time", "erste Zeit"),
    ("last man", "letzter Mann"),
    ("long way", "langer Weg"),
    ("great way", "großartiger Weg"),
    ("a great person", "eine großartige Person"),
    ("an important thing", "eine wichtige Sache"),
    ("new day", "neuer Tag"),
    ("good way", "guter Weg"),
    ("great time", "großartige Zeit"),
    ("little way", "kleiner Weg"),
    ("first thing", "erste Sache"),
    ("last day", "letzter Tag"),
    ("long thing", "lange Sache"),
    ("great man", "großartiger Mann"),
    ("little person", "kleine Person"),
    ("a good day", "ein guter Tag"),
    ("an important way", "ein wichtiger Weg"),
    ("new person", "neue Person"),
    ("good time", "gute Zeit"),
    ("great year", "großartiges Jahr"),
    ("little time", "kurze Zeit"),
    ("first year", "erstes Jahr"),
    ("last thing", "letzte Sache"),
    ("long year", "langes Jahr"),
    ("great thing", "großartige Sache"),
    ("little man", "kleiner Mann"),
    ("a long way", "ein langer Weg"),
    ("an important person", "eine wichtige Person"),
    ("new time", "neue Zeit"),
    ("good year", "gutes Jahr"),
    ("great way", "großartiger Weg"),
    ("little thing", "kleine Sache"),
    ("first day", "erster Tag"),
    ("last person", "letzte Person"),
    ("long time", "lange Zeit"),
    ("great day", "großartiger Tag"),
    ("little way", "kleiner Weg"),
    ("a new year", "ein neues Jahr"),
    ("an important day", "ein wichtiger Tag"),
    ("new way", "neuer Weg"),
    ("good man", "guter Mann"),
    ("great person", "großartige Person"),
    ("little year", "kleines Jahr"),
    ("first time", "erste Zeit"),
    ("last way", "letzter Weg"),
    ("long person", "lange Person"),
    ("great year", "großartiges Jahr"),
    ("little day", "kleiner Tag"),
    ("a great time", "eine großartige Zeit"),
    ("an important thing", "eine wichtige Sache"),
    ("new person", "neue Person"),
    ("good way", "guter Weg"),
    ("great man", "großartiger Mann"),
    ("little time", "kurze Zeit"),
    ("first year", "erstes Jahr"),
    ("last thing", "letzte Sache"),
    ("long way", "langer Weg"),
    ("great day", "großartiger Tag"),
    ("little thing", "kleine Sache"),
    ("a first way", "ein erster Weg"),
    ("an important man", "ein wichtiger Mann"),
    ("new year", "neues Jahr"),
    ("good time", "gute Zeit"),
    ("great person", "großartige Person"),
    ("little way", "kleiner Weg"),
    ("first day", "erster Tag"),
    ("last year", "letztes Jahr"),
    ("long time", "lange Zeit"),
    ("great way", "großartiger Weg"),
    ("little person", "kleine Person")
]


for i in word_pairs:
    continue
    res = [i[0], i[1]]
    for j in range(6):
        res[0] += ' ' + i[0]
        res[1] += ' ' + i[1]
    sentence_pairs.append((res[0] + ' ', res[1] + ' '))
    sentence_pairs.append((res[0] + '.', res[1] + '.'))
for i in range(len(sentence_pairs)):
    res = list(sentence_pairs[i])
    sentence_pairs[i] = (res[0] + ' ', res[1] + ' ')
    continue
    sentence_pairs[i] = list(sentence_pairs[i])
    sentence_pairs[i][0] = '$ ' + sentence_pairs[i][0] + ' $'
    sentence_pairs[i][1] = '$ ' + sentence_pairs[i][1] + ' $'