import numpy as np

special_chars = ['„', '”', '"', '\'', '.', ',', '/', '\\', ' ', '   ', '*', ';', ':', '`', '[', ']', '{', '}', '!', '?', '\n', '$']
'''sentence_pairs = [
    ("The dog ran to the tree", "Der Hund rannte zum Baum"),
    ("I want to eat good food", "Ich möchte gutes Essen essen"),
    ("The cat played with the mouse", "Die Katze spielte mit der Maus"),
    ("We saw a bear in the forest", "Wir sahen einen Bären im Wald"),
    ("The boy laughed at the funny story", "Der Junge lachte über die lustige Geschichte"),
    ("She found a red book on the bed", "Sie fand ein rotes Buch auf dem Bett"),
    ("The bird flew over the green garden", "Der Vogel flog über den grünen Garten"),
    ("He stopped to look at the blue sky", "Er hielt an, um den blauen Himmel zu betrachten"),
    ("The fish swam in the cold river", "Der Fisch schwamm im kalten Fluss"),
    ("They walked through the dark forest", "Sie gingen durch den dunklen Wald"),
    ("I will take my dog for a walk", "Ich werde mit meinem Hund spazieren gehen"),
    ("She has a beautiful garden at home", "Sie hat einen schönen Garten zu Hause"),
    ("Can you help me with my homework", "Kannst du mir bei meinen Hausaufgaben helfen"),
    ("The children are playing in the park", "Die Kinder spielen im Park"),
    ("I found my keys under the table", "Ich fand meine Schlüssel unter dem Tisch"),
    ("He is reading a book about magic", "Er liest ein Buch über Magie"),
    ("We will go to the beach tomorrow", "Wir werden morgen zum Strand gehen"),
    ("She loves to dance in the rain", "Sie liebt es, im Regen zu tanzen"),
    ("They are watching a movie tonight", "Sie sehen sich heute Abend einen Film an"),
    ("I need to buy some new clothes", "Ich muss einige neue Kleider kaufen"),
    ("The sun is shining brightly today", "Die Sonne scheint heute hell"),
    ("He has a big smile on his face", "Er hat ein großes Lächeln im Gesicht"),
    ("She enjoys reading stories before bed", "Sie liest gerne Geschichten vor dem Schlafengehen"),
    ("We will visit our grandparents this weekend", "Wir werden unsere Großeltern am Wochenende besuchen"),
    ("The flowers are blooming in spring", "Die Blumen blühen im Frühling"),
    ("I like to drink tea in the morning", "Ich trinke gerne Tee am Morgen"),
    ("He plays soccer every Saturday afternoon", "Er spielt jeden Samstagnachmittag Fußball"),
    ("The baby is sleeping in her crib", "Das Baby schläft in ihrem Bettchen"),
    ("They have a picnic by the lake", "Sie haben ein Picknick am See"),
    ("She is painting a picture of a mountain", "Sie malt ein Bild von einem Berg"),
    ("I saw a fox running across the field", "Ich sah einen Fuchs über das Feld laufen"),
    ("He likes to ride his bike after school", "Er fährt nach der Schule gerne mit seinem Fahrrad"),
    ("We are going to have a party next week", "Wir werden nächste Woche eine Party haben"),
    ("The stars are shining in the night sky", "Die Sterne leuchten am Nachthimmel"),
    ("She baked cookies for her friends", "Sie backte Kekse für ihre Freunde"),
    ("He found an old coin in the garden", "Er fand eine alte Münze im Garten"),
    ("They are playing cards at the table", "Sie spielen Karten am Tisch"),
    ("I want to learn how to play guitar", "Ich möchte lernen, wie man Gitarre spielt"),
    ("The train arrived at the station on time", "Der Zug kam pünktlich am Bahnhof an"),
    ("She wore a beautiful dress to the party", "Sie trug ein schönes Kleid zur Party"),
    ("We saw many birds flying south for winter", "Wir sahen viele Vögel nach Süden fliegen für den Winter"),
    ("He took his dog for a walk in the evening", "Er ging abends mit seinem Hund spazieren"),
    ("I will call you later this afternoon", "Ich werde dich später am Nachmittag anrufen"),
    ("They built a sandcastle on the beach"," Sie bauten eine Sandburg am Strand"), 
    ("She loves to swim in the ocean"," Sie liebt es, im Ozean zu schwimmen"), 
    ("He has many friends at school"," Er hat viele Freunde in der Schule"), 
    ("We went hiking in the mountains last weekend"," Wir sind letztes Wochenende in den Bergen wandern gegangen"), 
    ("The children played games outside all day"," Die Kinder spielten den ganzen Tag draußen Spiele"), 
    ("I bought some apples and oranges at the store"," Ich kaufte Äpfel und Orangen im Laden"), 
    ("She enjoys listening to music while studying"," Sie hört gerne Musik während des Studierens"), 
    ("They visited a museum during their trip"," Sie besuchten ein Museum während ihrer Reise"), 
    ("He wrote a letter to his pen pal"," Er schrieb einen Brief an seinen Brieffreund"), 
    ("We had fun playing board games together"," Wir hatten Spaß beim Spielen von Brettspielen zusammen"), 
    ("The sky turned dark before it started raining"," Der Himmel wurde dunkel, bevor es zu regnen begann"), 
    ("She made a cake for her friend's birthday"," Sie machte einen Kuchen zum Geburtstag ihrer Freundin"), 
    ("He likes to draw pictures of animals"," Er zeichnet gerne Bilder von Tieren"), 
    ("We watched fireworks on New Year's Eve"," Wir sahen Feuerwerke an Silvester"), 
    ("The library has many interesting books"," Die Bibliothek hat viele interessante Bücher"), 
    ("I enjoy taking long walks in nature"," Ich genieße es, lange Spaziergänge in der Natur zu machen"), 
    ("They celebrated their anniversary with dinner out"," Sie feierten ihren Jahrestag mit einem Abendessen draußen"), 
    ("She feels happy when she helps others"," Sie fühlt sich glücklich, wenn sie anderen hilft"), 
    ("He always finds time to read before bed"," Er findet immer Zeit, vor dem Schlafengehen zu lesen"), 
    ("We learned about different cultures in class"," Wir lernten über verschiedene Kulturen im Unterricht"), 
    ("The dog barked loudly when strangers arrived"," Der Hund bellte laut, als Fremde ankamen"), 
    ("She took beautiful photos during her vacation"," Sie machte wunderschöne Fotos während ihres Urlaubs"), 
    ("They enjoyed watching movies together on weekends"," Sie genossen es, am Wochenende zusammen Filme zu schauen"), 
    ("He fixed his bike after it broke down"," Er reparierte sein Fahrrad, nachdem es kaputt gegangen war"), 
    ("We planted flowers in our garden last spring"," Wir pflanzten Blumen in unserem Garten letzten Frühling"), 
    ("She likes to collect stamps from different countries"," Sie sammelt gerne Briefmarken aus verschiedenen Ländern"), 
    ("He plays basketball every Friday evening"," Er spielt jeden Freitagabend Basketball"), 
    ("We had a barbecue party last summer"," Wir hatten letzten Sommer eine Grillparty"), 
    ("The teacher explained the lesson clearly"," Der Lehrer erklärte die Lektion klar und deutlich"), 
    ("I found my favorite shirt at the store yesterday"," Ich fand mein Lieblingshemd gestern im Laden"), 
    ("They went camping in the woods last weekend"," Sie gingen letztes Wochenende campen im Wald"), 
    ("She enjoys painting landscapes and portraits"," Sie malt gerne Landschaften und Porträts"), 
    ("He always helps his neighbors with their chores"," Er hilft immer seinen Nachbarn bei ihren Aufgaben"), 
    ("We visited our relatives during the holidays"," Wir besuchten unsere Verwandten während der Feiertage"), 
    ("The children played soccer until sunset"," Die Kinder spielten Fußball bis zum Sonnenuntergang"), 
    ("She baked cookies for her classmates' party"," Sie backte Kekse für die Party ihrer Klassenkameraden"), 
    ("He enjoys fishing by the lake on weekends"," Er angelt gerne am See an den Wochenenden"), 
    ("We watched documentaries about nature and wildlife"," Wir sahen Dokumentationen über die Natur und Wildtiere") ,  
      ('I like to drink coffee every morning', 'Ich trinke jeden Morgen gerne Kaffee'),
      ('The children are excited about their trip', 'Die Kinder sind aufgeregt wegen ihrer Reise'),
      ('She enjoys reading books before going to sleep', 'Sie liest gerne Bücher, bevor sie schlafen geht'),
      ('He plays video games with his friends online', 'Er spielt online Videospiele mit seinen Freunden'),
      ('We often go hiking during our vacations', 'Wir gehen oft wandern während unserer Ferien'),
      ('The cat sleeps on the windowsill every day', 'Die Katze schläft jeden Tag auf der Fensterbank'),
      ('They love watching cartoons on Saturday mornings', 'Sie lieben es, samstags morgens Cartoons zu schauen'),
      ('I found an interesting article online yesterday', 'Ich fand gestern einen interessanten Artikel online'),
      ('She is learning how to play piano this year', 'Sie lernt dieses Jahr, wie man Klavier spielt'),
      ('We had fun playing games at the party', 'Wir hatten Spaß beim Spielen von Spielen auf der Party'),
      ('The sun sets beautifully over the mountains', 'Die Sonne geht schön über den Bergen unter'),
      ('He enjoys cooking new recipes for dinner', 'Er kocht gerne neue Rezepte zum Abendessen'),
      ('They went for a walk along the riverbank', 'Sie gingen am Ufer des Flusses spazieren'),
      ('I want to travel around Europe next summer', 'Ich möchte nächsten Sommer durch Europa reisen'),
      ('She loves taking photographs of nature', 'Sie liebt es, Fotos von der Natur zu machen'),
      ('He often visits his grandparents on weekends', 'Er besucht oft seine Großeltern am Wochenende'),
      ('We built a snowman during winter vacation', 'Wir bauten einen Schneemann während der Winterferien'),
      ('The flowers bloom beautifully in spring', 'Die Blumen blühen schön im Frühling'),
      ('I enjoy listening to music while studying', 'Ich höre gerne Musik beim Lernen'),
      ('They celebrated their victory with a party', 'Sie feierten ihren Sieg mit einer Party')]

sentence_pairs += [
    ('water', 'Wasser'),
    ('away', 'weg'),
    ('good', 'gut'),
    ('want', 'wollen'),
    ('over', 'über'),
    ('how', 'wie'),
    ('did', 'tat'),
    ('man', 'Mann'),
    ('going', 'gehen'),
    ('where', 'wo'),
    ('would', 'würde'),
    ('or', 'oder'),
    ('took', 'nahm'),
    ('school', 'Schule'),
    ('think', 'denken'),
    ('home', 'Zuhause'),
    ('who', 'wer'),
    ('didn', 'nicht'),  # "didn't" is often translated as "nicht"
    ('ran', 'rannte'),
    ('know', 'wissen'),
    ('bear', 'Bär'),  # Can also mean "tragen" in different contexts
    ('can', 'können'),
    ('again', 'wieder'),
    ('cat', 'Katze'),
    ('long', 'lang'),
    ('things', 'Dinge'),
    ('new', 'neu'),
    ('after', 'nach'),
    ('wanted', 'wollte'),
    ('eat', 'essen'),
    ('everyone', 'jeder'),  # Can also mean "alle"
    ('our', 'unser'),
    ('two', 'zwei'),
    ('has', 'hat'),
    ('yes', 'ja'),
    ('play', 'spielen'),
    ('take', 'nehmen'),
    ('thought', 'Gedanke'),  # Can also mean "dachte" (past tense of think)
    ('dog', 'Hund'),
    ('well', 'gut'),  # Can also mean "brunnen" in different contexts
    ('find', 'finden'),
    ('more', 'mehr'),
    ('I', 'ich'),
    ("ll", "werde"),  # Short for "will" in future tense
    ("round", "rund"),
    ("tree", "Baum"),
    ("magic", "Magie"),
    ("shouted", "rief"),
    ("us", "uns"),
    ("other", "anderer"),
    ("food", "Essen"),
    ("fox", "Fuchs"),
    ("through", "durch"),
    ("way", "Weg"),
    ("been", "gewesen"),
    ("stop", "stoppen"),
    ("must", "müssen"),
    ("red", "rot"),
    ("door", "Tür"),
    ("right", "rechts"),  # Can also mean "richtig"
    ("sea", "Meer"),
    ("these", "diese"),
    ("began", "begann"),
    ("boy", "Junge"),
    ("animals", "Tiere"),
    ("never", "nie"),
    ("next", "nächster"),
    ("first", "erste"),
    ("work", "Arbeit"),  # Can also mean "arbeiten" (to work)
    ("lots", "viele"),  # Can also mean 'eine Menge'
    ("need", "brauchen"),
   ("that", "dass"), 
   ("baby", "Baby"), 
   ("fish", "Fisch"), 
   ("gave", "gab"), 
   ("mouse", "Maus"), 
   ("something", "etwas"), 
   ("bed", "Bett"), 
   ("may", "dürfen"), 
   ("still", "noch"), 
   ("found", "fand"), 
   ("live", "leben"), 
   ("say", "sagen"), 
   ("soon", "bald"), 
   ("night", "Nacht"), 
   ("narrator", "Erzähler"), 
   ("small", "klein"), 
   ("car", "Auto"), 
   ("couldn", 'konnte nicht'),  
   ('t', 't'),  
   ('three', 'drei'),  
   ('head', 'Kopf'),  
   ('king', 'König'),  
   ('town', 'Stadt'),  
   ('I', 'ich'),  
   ('ve', 'habe'),  
   ('around', 'herum'),  
   ('every', 'jeder'),  
   ('garden', 'Garten'),  
   ('fast', 'schnell'),  
   ('only', 'nur'),  
   ('many', 'viele'),  
   ('laughed', 'lachte'),  
   ('let', 'lassen'),  
   ('much', 'viel'),  
   ('suddenly', 'plötzlich'),  
   ('told', 'sagte'),  
   ('another', 'ein anderer'),  
   ('great', 'großartig'),  
   ('why', 'warum'),  
  ('cried', 'schrie'),
  ('keep', 'behalten'),
  ('room', 'Zimmer'),
  ('last', 'letzte'),
  ('jumped', 'sprang'),
  ('because', 'weil'),
  ('even', 'sogar'),
  ('am', 'bin'),
  ('before', 'vor'),
  ('gran', 'Oma'),
  ('clothes', 'Kleidung'),
  ('tell', 'erzählen'),
  ('key', 'Schlüssel'),
  ('fun', 'Spaß'),
  ('place', 'Platz'),
  ('mother', 'Mutter'),
  ('sat', 'saß'),
  ('boat', 'Boot'),
  ('window', 'Fenster'),
  ('sleep', 'schlafen'),
  ('feet', 'Füße'),
("morning","morgen"),
("queen","Königin"),
("each","jeder"),
("book","Buch"),
("its","sein"),
("green","grün"),
("different","anders"),
("let","lassen"),
("girl","Mädchen"),
("which","welches"),
("inside","drinnen"),
("run","laufen"),
("any","irgendwelche"),
("under","unter"),
("hat","Hut"),
("snow","Schnee"),
("air","Luft"),
("trees","Bäume"),
("bad","schlecht"),
("tea","Tee"),
("top","oben"),
("eyes","Augen"),
("fell","fiel"),
("friends","Freunde"),
("box","Kiste"),
("dark","dunkel"),
("grandad","Opa"),
("there","da"),
("looking","schauend"),
("end","Ende"),
("than","als"),
("best","beste"),
("better","besser"),
("hot","heiß"),
("sun","Sonne"),
("across","über"),
("gone","weg"),
("hard","hart"),
("floppy","schlaff"),
("really","wirklich"),
("wind","Wind"),
("wish","Wunsch"),
("eggs","Eier"),
("once","einmal"),
("please","bitte"),
("thing","Ding"),
("stopped","hörte auf"),
("ever","jemals"),
("miss","verpassen"),
("most","meistens"),
("cold","kalt"),
("park","Park"),
("lived","lebte"),
("birds","Vögel"),
("duck","Ente"),
("horse","Pferd"),
("rabbit","Kaninchen"),
("white","weiß"),   
('coming','kommen'),    
('he','er'),    
('s','s'),    
('river','Fluss'),    
('liked','mochte'),    
('giant','Riese'),    
('looks','Aussehen'),    
('use','benutzen'),    
('along','entlang'),    
('plants','Pflanzen'),    
('dragon','Drache'),    
('pulled','zog'),    
('we','wir'),    
('re','sind'),    
('fly','fliegen'),    
('grow','wachsen'),    
('make','machen')
]

sentence_pairs += [
    ("I am a good person", "Ich bin ein guter Mensch"),
    ("You are a great man", "Du bist ein großartiger Mann"),
    ("He is a new person", "Er ist eine neue Person"),
    ("She has a long way to go", "Sie hat einen langen Weg vor sich"),
    ("It is a good day", "Es ist ein guter Tag"),
    
    ("We have a great time", "Wir haben eine großartige Zeit"),
    ("They do a good job", "Sie machen einen guten Job"),
    ("I say it is good", "Ich sage, es ist gut"),
    ("You get a new thing", "Du bekommst eine neue Sache"),
    ("He makes a good plan", "Er macht einen guten Plan"),

    ("She goes to the park", "Sie geht zum Park"),
    ("It is a long year", "Es ist ein langes Jahr"),
    ("We do it every day", "Wir machen es jeden Tag"),
    ("They have a little time", "Sie haben wenig Zeit"),
    ("I want to go home", "Ich möchte nach Hause gehen"),

    ("You have a good idea", "Du hast eine gute Idee"),
    ("He is a great man", "Er ist ein großartiger Mann"),
    ("She has a new plan", "Sie hat einen neuen Plan"),
    ("It is a good thing", "Es ist eine gute Sache"),
    ("We say it is great", "Wir sagen, es ist großartig"),

    ("They get a new year", "Sie bekommen ein neues Jahr"),
    ("I make a good choice", "Ich treffe eine gute Wahl"),
    ("You are a good friend", "Du bist ein guter Freund"),
    ("He has a long way to go", "Er hat einen langen Weg vor sich"),
    ("She does a great job", "Sie macht einen großartigen Job"),

    # Continuing with more sentences:
    
    ('It is a new day', 'Es ist ein neuer Tag'), 
    ('We have a long time', 'Wir haben viel Zeit'), 
    ('They say it is good', 'Sie sagen, es ist gut'), 
    ('I get a new job', 'Ich bekomme einen neuen Job'), 
    ('You make a good plan', 'Du machst einen guten Plan'), 
   
   ('He goes to the store', 'Er geht zum Laden'), 
   ('She is a good friend', 'Sie ist eine gute Freundin'), 
   ('It is a great year', 'Es ist ein großartiges Jahr'), 
   ('We do it the right way', 'Wir machen es auf die richtige Weise'), 
   ('They have little time', 'Sie haben wenig Zeit'), 
   
   ('I want to be great', 'Ich möchte großartig sein'), 
   ('You are a new person', 'Du bist eine neue Person'), 
   ('He has a good idea', 'Er hat eine gute Idee'), 
   ('She makes a great choice', 'Sie trifft eine großartige Wahl'), 
   ('It is a long way', 'Es ist ein weiter Weg'), 

   ('We say it is new', 'Wir sagen, es ist neu'), 
   ('They get a good time', 'Sie haben eine gute Zeit'), 
   ('I do it every year', 'Ich mache es jedes Jahr'), 
   ('You have a great plan', 'Du hast einen großartigen Plan'), 
   ('He is a little man', 'Er ist ein kleiner Mann'), 

   ('She goes the long way', 'Sie geht den langen Weg'), 
   ('It is a good year', 'Es ist ein gutes Jahr'), 
   ('We make a new plan', 'Wir machen einen neuen Plan'), 
   ('They say it is great', 'Sie sagen, es ist großartig'), 
   ('I want to have fun', 'Ich möchte Spaß haben'),

   # Final sentences:
   ('You are my best friend', 'Du bist mein bester Freund'), 
   ('He will be here soon', 'Er wird bald hier sein'), 
   ('She can make it happen', 'Sie kann es möglich machen'), 
   ('It feels like the first day of summer', 'Es fühlt sich an wie der erste Sommertag')]
'''

sentence_pairs = [
    ("the person has a new way to make the old thing go last", "die Person hat einen neuen Weg die alte Sache gehen zu letzte"),
    ("she is a good man he makes the great day important", "sie ist ein guter Mann er den großen Tag wichtig macht"),
    ("we have a great day and we make the last thing new", "wir haben einen großen Tag und wir machen die letzte Sache neu"),
    ("they make an old thing and they have the first time", "sie machen eine alte Sache und sie haben die erste Zeit"),
    ("he does the last year and he is the new way to go", "er macht das letzte Jahr und er ist der neue Weg zu gehen"),
    ("i am the first time and i have the great day to make", "ich bin die erste Zeit und ich habe den großen Tag zu machen"),
    ("it is a little thing but it makes the new way important", "es ist eine kleine Sache aber es macht den neuen Weg wichtig"),
    ("you are an important person and you have the last year", "du bist eine wichtige Person und du hast das letzte Jahr"),
    ("the man has a new way and he makes the old thing go", "der Mann hat einen neuen Weg und er macht die alte Sache gehen"),
    ("she is the last year and she has the great day to make", "sie ist das letzte Jahr und sie hat den großen Tag zu machen"),
    ("we have a great time and we make the last thing new", "wir haben eine große Zeit und wir machen die letzte Sache neu"),
    ("they make a good day and they have the first time to go", "sie machen einen guten Tag und sie haben die erste Zeit zu gehen"),
    ("he does the first thing and he is the new way to make", "er macht die erste Sache und er ist der neue Weg zu machen"),
    ("i am an old person and i have the great day to go", "ich bin eine alte Person und ich habe den großen Tag zu gehen"),
    ("it is a little way but it makes the new thing important", "es ist ein kleiner Weg aber es macht die neue Sache wichtig"),
    ("you are the new man and you have the last time to make", "du bist der neue Mann und du hast die letzte Zeit zu machen"),
    ("the person is a good year and she makes the old thing go", "die Person ist ein gutes Jahr und sie macht die alte Sache gehen"),
    ("she has the last time and she makes the great day new", "sie hat die letzte Zeit und sie macht den großen Tag neu"),
    ("we have an important day and we make the last thing go", "wir haben einen wichtigen Tag und wir machen die letzte Sache gehen"),
    ("they make a little thing and they have the first time to go", "sie machen eine kleine Sache und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new person to make", "er macht den großen Weg und er ist die neue Person zu machen"),
    ("i am a little year and i have the great day to make", "ich bin ein kleine Jahr und ich habe den großen Tag zu machen"),
    ("it is the first day and it makes the new way important", "es ist der erste Tag und es macht den neuen Weg wichtig"),
    ("you are a good way and you have the last time to make", "du bist ein guter Weg und du hast die letzte Zeit zu machen"),
    ("the person has an old thing and she makes the new way go", "die Person hat eine alte Sache und sie macht den neuen Weg gehen"),
    ("she is the great man and she has the last year to make", "sie ist der große Mann und sie hat das letzte Jahr zu machen"),
    ("we have a new year and we make the great day important", "wir haben ein neue Jahr und wir machen den großen Tag wichtig"),
    ("they make the last time and they have the first thing to go", "sie machen die letzte Zeit und sie haben die erste Sache zu gehen"),
    ("he does a little day and he is the new way to make", "er macht einen kleinen Tag und er ist der neue Weg zu machen"),
    ("i am the important way and i have the last year to go", "ich bin der wichtige Weg und ich habe das letzte Jahr zu gehen"),
    ("it is a good person and it makes the old thing new", "es ist eine gute Person und es macht die alte Sache neu"),
    ("you are the old man and you have the first time to make", "du bist der alte Mann und du hast die erste Zeit zu machen"),
    ("the man has the first thing and he makes the new way go", "der Mann hat die erste Sache und er macht den neuen Weg gehen"),
    ("she is a little year and she has the great day to make", "sie ist ein kleine Jahr und sie hat den großen Tag zu machen"),
    ("we have the great day and we make the last thing new", "wir haben den großen Tag und wir machen die letzte Sache neu"),
    ("they make an important time and they have the first way to go", "sie machen eine wichtige Zeit und sie haben den ersten Weg zu gehen"),
    ("he does the new way and he is the great person to make", "er macht den neuen Weg und er ist die große Person zu machen"),
    ("i am a good person and i have the last time to go", "ich bin eine gute Person und ich habe die letzte Zeit zu gehen"),
    ("it is the last year and it makes the new thing important", "es ist das letzte Jahr und es macht die neue Sache wichtig"),
    ("you are a little thing and you have the great day to make", "du bist eine kleine Sache und du hast den großen Tag zu machen"),
    ("the person is the great man and she makes the old thing go", "die Person ist der große Mann und sie macht die alte Sache gehen"),
    ("she has an old day and she makes the new way important", "sie hat einen alten Tag und sie macht den neuen Weg wichtig"),
    ("we have the first time and we make the last thing go", "wir haben die erste Zeit und wir machen die letzte Sache gehen"),
    ("they make a good way and they have the last year to make", "sie machen einen guten Weg und sie haben das letzte Jahr zu machen"),
    ("he does the important year and he is the new way to go", "er macht das wichtige Jahr und er ist der neue Weg zu gehen"),
    ("i am the new thing and i have the great day to make", "ich bin die neue Sache und ich habe den großen Tag zu machen"),
    ("it is a little person and it makes the old way new", "es ist eine kleine Person und es macht den alten Weg neu"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the last day and he makes the new thing go", "der Mann hat den letzten Tag und er macht die neue Sache gehen"),
    ("she is a good year and she has the great day to make", "sie ist ein gutes Jahr und sie hat den großen Tag zu machen"),
    ("we have an old time and we make the first thing new", "wir haben eine alte Zeit und wir machen die erste Sache neu"),
    ("they make the first thing and they have the last way to go", "sie machen die erste Sache und sie haben den letzten Weg zu gehen"),
    ("he does a little way and he is the new person to make", "er macht einen kleinen Weg und er ist die neue Person zu machen"),
    ("i am the important person and i have the last year to go", "ich bin die wichtige Person und ich habe das letzte Jahr zu gehen"),
    ("it is the new man and it makes the great day important", "es ist der neue Mann und es macht den großen Tag wichtig"),
    ("you are a great day and you have the last time to make", "du bist ein großer Tag und du hast die letzte Zeit zu machen"),
    ("the person has a good time and she makes the old thing go", "die Person hat eine gute Zeit und sie macht die alte Sache gehen"),
    ("she is the little thing and she has the great day to make", "sie ist die kleine Sache und sie hat den großen Tag zu machen"),
    ("we have the important year and we make the last thing new", "wir haben das wichtige Jahr und wir machen die letzte Sache neu"),
    ("they make an old way and they have the first time to go", "sie machen einen alten Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great person and he is the new way to make", "er macht die große Person und er ist der neue Weg zu machen"),
    ("i am a new day and i have the last time to go", "ich bin ein neue Tag und ich habe die letzte Zeit zu gehen"),
    ("it is the first way and it makes the new thing important", "es ist der erste Weg und es macht die neue Sache wichtig"),
    ("you are the good year and you have the last time to make", "du bist das gute Jahr und du hast die letzte Zeit zu machen"),
    ("the man has the great time and he makes the old thing go", "der Mann hat die große Zeit und er macht die alte Sache gehen"),
    ("she is an important thing and she has the last year to make", "sie ist eine wichtige Sache und sie hat das letzte Jahr zu machen"),
    ("we have a little day and we make the last person new", "wir haben einen kleinen Tag und wir machen die letzte Person neu"),
    ("they make the last person and they have the first way to go", "sie machen die letzte Person und sie haben den ersten Weg zu gehen"),
    ("he does a good way and he is the new year to make", "er macht einen guten Weg und er ist das neue Jahr zu machen"),
    ("i am the old year and i have the last time to go", "ich bin das alte Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is a new thing and it makes the great day important", "es ist eine neue Sache und es macht den großen Tag wichtig"),
    ("you are the little man and you have the last time to make", "du bist der kleine Mann und du hast die letzte Zeit zu machen"),
    ("the person is the first day and she makes the new way go", "die Person ist der erste Tag und sie macht den neuen Weg gehen"),
    ("she has a great way and she makes the old thing new", "sie hat einen großen Weg und sie macht die alte Sache neu"),
    ("we have an important thing and we make the last time go", "wir haben eine wichtige Sache und wir machen die letzte Zeit gehen"),
    ("they make a little time and they have the first way to go", "sie machen eine kleine Zeit und sie haben den ersten Weg zu gehen"),
    ("he does the new person and he is the great way to make", "er macht die neue Person und er ist der große Weg zu machen"),
    ("i am a good way and i have the last year to go", "ich bin ein guter Weg und ich habe das letzte Jahr zu gehen"),
    ("it is the last thing and it makes the new way important", "es ist die letzte Sache und es macht den neuen Weg wichtig"),
    ("you are the great year and you have the last time to make", "du bist das große Jahr und du hast die letzte Zeit zu machen"),
    ("the man has an old person and he makes the new way go", "der Mann hat eine alte Person und er macht den neuen Weg gehen"),
    ("she is the first time and she has the great day to make", "sie ist die erste Zeit und sie hat den großen Tag zu machen"),
    ("we have a good day and we make the last thing new", "wir haben einen guten Tag und wir machen die letzte Sache neu"),
    ("they make the important way and they have the first time to go", "sie machen den wichtigen Weg und sie haben die erste Zeit zu gehen"),
    ("he does a little thing and he is the new year to make", "er macht eine kleine Sache und er ist das neue Jahr zu machen"),
    ("i am the new year and i have the last time to go", "ich bin das neue Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is a great man and it makes the old thing new", "es ist ein großer Mann und es macht die alte Sache neu"),
    ("you are the old way and you have the last time to make", "du bist der alte Weg und du hast die letzte Zeit zu machen"),
    ("the person has the last thing and she makes the new way go", "die Person hat die letzte Sache und sie macht den neuen Weg gehen"),
    ("she is a little person and she has the great day to make", "sie ist eine kleine Person und sie hat den großen Tag zu machen"),
    ("we have the great year and we make the last thing new", "wir haben das große Jahr und wir machen die letzte Sache neu"),
    ("they make an old day and they have the first way to go", "sie machen einen alten Tag und sie haben den ersten Weg zu gehen"),
    ("he does the first way and he is the new person to make", "er macht den ersten Weg und er ist die neue Person zu machen"),
    ("i am a good thing and i have the last time to go", "ich bin eine gute Sache und ich habe die letzte Zeit zu gehen"),
    ("it is the new time and it makes the great day important", "es ist die neue Zeit und es macht den großen Tag wichtig"),
    ("you are the little year and you have the last time to make", "du bist das kleine Jahr und du hast die letzte Zeit zu machen"),
    ("the man has a great person and he makes the old thing go", "der Mann hat eine große Person und er macht die alte Sache gehen"),
    ("she is the important day and she has the last year to make", "sie ist der wichtige Tag und sie hat das letzte Jahr zu machen"),
    ("we have a little way and we make the last time go", "wir haben einen kleinen Weg und wir machen die letzte Zeit gehen"),
    ("they make the last time and they have the first thing to go", "sie machen die letzte Zeit und sie haben die erste Sache zu gehen"),
    ("he does an old thing and he is the new way to make", "er macht eine alte Sache und er ist der neue Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is a good day and it makes the new thing important", "es ist ein guter Tag und es macht die neue Sache wichtig"),
    ("you are the new time and you have the last year to make", "du bist die neue Zeit und du hast das letzte Jahr zu machen"),
    ("the person has the first year and she makes the old thing go", "die Person hat das erste Jahr und sie macht die alte Sache gehen"),
    ("she is a little way and she has the great day to make", "sie ist ein kleiner Weg und sie hat den großen Tag zu machen"),
    ("we have an important person and we make the last thing new", "wir haben eine wichtige Person und wir machen die letzte Sache neu"),
    ("they make a great thing and they have the first time to go", "sie machen eine große Sache und sie haben die erste Zeit zu gehen"),
    ("he does the last day and he is the new way to make", "er macht den letzten Tag und er ist der neue Weg zu machen"),
    ("i am a new way and i have the last time to go", "ich bin ein neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the old year and it makes the great day important", "es ist das alte Jahr und es macht den großen Tag wichtig"),
    ("you are the good thing and you have the last time to make", "du bist die gute Sache und du hast die letzte Zeit zu machen"),
    ("the man has a good thing and he makes the new way go", "der Mann hat eine gute Sache und er macht den neuen Weg gehen"),
    ("she is the new way and she has the last year to make", "sie ist der neue Weg und sie hat das letzte Jahr zu machen"),
    ("we have an old person and we make the great day new", "wir haben eine alte Person und wir machen den großen Tag neu"),
    ("they make the great time and they have the first way to go", "sie machen die große Zeit und sie haben den ersten Weg zu gehen"),
    ("he does a little year and he is the new way to make", "er macht ein kleine Jahr und er ist der neue Weg zu machen"),
    ("i am the first person and i have the last time to go", "ich bin die erste Person und ich habe die letzte Zeit zu gehen"),
    ("it is a great way and it makes the new thing important", "es ist ein großer Weg und es macht die neue Sache wichtig"),
    ("you are the old thing and you have the last time to make", "du bist die alte Sache und du hast die letzte Zeit zu machen"),
    ("the person has the important day and she makes the old thing go", "die Person hat den wichtigen Tag und sie macht die alte Sache gehen"),
    ("she is a little time and she has the great day to make", "sie ist eine kleine Zeit und sie hat den großen Tag zu machen"),
    ("we have the last person and we make the first thing new", "wir haben die letzte Person und wir machen die erste Sache neu"),
    ("they make a new way and they have the last time to go", "sie machen einen neuen Weg und sie haben die letzte Zeit zu gehen"),
    ("he does the great year and he is the new way to make", "er macht das große Jahr und er ist der neue Weg zu machen"),
    ("i am a good year and i have the last time to go", "ich bin ein gutes Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is the new person and it makes the great day important", "es ist die neue Person und es macht den großen Tag wichtig"),
    ("you are the little way and you have the last time to make", "du bist der kleine Weg und du hast die letzte Zeit zu machen"),
    ("the man has an important thing and he makes the new way go", "der Mann hat eine wichtige Sache und er macht den neuen Weg gehen"),
    ("she is the first day and she has the great time to make", "sie ist der erste Tag und sie hat die große Zeit zu machen"),
    ("we have a great person and we make the last thing new", "wir haben eine große Person und wir machen die letzte Sache neu"),
    ("they make the old time and they have the first way to go", "sie machen die alte Zeit und sie haben den ersten Weg zu gehen"),
    ("he does a good person and he is the new way to make", "er macht eine gute Person und er ist der neue Weg zu machen"),
    ("i am the last thing and i have the last time to go", "ich bin die letzte Sache und ich habe die letzte Zeit zu gehen"),
    ("it is a little day and it makes the new way important", "es ist ein kleiner Tag und es macht den neuen Weg wichtig"),
    ("you are the great person and you have the last time to make", "du bist die große Person und du hast die letzte Zeit zu machen"),
    ("the person has the new year and she makes the old thing go", "die Person hat das neue Jahr und sie macht die alte Sache gehen"),
    ("she is a good way and she has the great day to make", "sie ist ein guter Weg und sie hat den großen Tag zu machen"),
    ("we have the important way and we make the last time go", "wir haben den wichtigen Weg und wir machen die letzte Zeit gehen"),
    ("they make a little day and they have the first way to go", "sie machen einen kleinen Tag und sie haben den ersten Weg zu gehen"),
    ("he does the old person and he is the new way to make", "er macht die alte Person und er ist der neue Weg zu machen"),
    ("i am the great year and i have the last time to go", "ich bin das große Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is a new person and it makes the great day important", "es ist eine neue Person und es macht den großen Tag wichtig"),
    ("you are the first way and you have the last time to make", "du bist der erste Weg und du hast die letzte Zeit zu machen"),
    ("the man has a little thing and he makes the new way go", "der Mann hat eine kleine Sache und er macht den neuen Weg gehen"),
    ("she is the last person and she has the great day to make", "sie ist die letzte Person und sie hat den großen Tag zu machen"),
    ("we have a good way and we make the last year new", "wir haben einen guten Weg und wir machen das letzte Jahr neu"),
    ("they make the important year and they have the first time to go", "sie machen das wichtige Jahr und sie haben die erste Zeit zu gehen"),
    ("he does a great day and he is the new way to make", "er macht einen großen Tag und er ist der neue Weg zu machen"),
    ("i am the old way and i have the last time to go", "ich bin der alte Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little year and it makes the new way important", "es ist das kleine Jahr und es macht den neuen Weg wichtig"),
    ("you are the new person and you have the last time to make", "du bist die neue Person und du hast die letzte Zeit zu machen"),
    ("the person has the great thing and she makes the old way go", "die Person hat die große Sache und sie macht den alten Weg gehen"),
    ("she is an important way and she has the last year to make", "sie ist ein wichtige Weg und sie hat das letzte Jahr zu machen"),
    ("we have a little time and we make the last way go", "wir haben eine kleine Zeit und wir machen den letzten Weg gehen"),
    ("they make the last way and they have the first thing to go", "sie machen den letzten Weg und sie haben die erste Sache zu gehen"),
    ("he does the first year and he is the new way to make", "er macht das erste Jahr und er ist der neue Weg zu machen"),
    ("i am a great person and i have the last time to go", "ich bin eine große Person und ich habe die letzte Zeit zu gehen"),
    ("it is the good way and it makes the old thing new", "es ist der gute Weg und es macht die alte Sache neu"),
    ("you are the old year and you have the last time to make", "du bist das alte Jahr und du hast die letzte Zeit zu machen"),
    ("the man has the new thing and he makes the great way go", "der Mann hat die neue Sache und er macht den großen Weg gehen"),
    ("she is a little person and she has the great day to make", "sie ist eine kleine Person und sie hat den großen Tag zu machen"),
    ("we have the great way and we make the last thing new", "wir haben den großen Weg und wir machen die letzte Sache neu"),
    ("they make an important day and they have the first way to go", "sie machen einen wichtigen Tag und sie haben den ersten Weg zu gehen"),
    ("he does a last thing and he is the new way to make", "er macht eine letzte Sache und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is a great person and it makes the old thing new", "es ist eine große Person und es macht die alte Sache neu"),
    ("you are the little thing and you have the last time to make", "du bist die kleine Sache und du hast die letzte Zeit zu machen"),
    ("the person has the old time and she makes the new way go", "die Person hat die alte Zeit und sie macht den neuen Weg gehen"),
    ("she is the good year and she has the great day to make", "sie ist das gute Jahr und sie hat den großen Tag zu machen"),
    ("we have a new way and we make the last thing new", "wir haben einen neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little person and they have the first way to go", "sie machen die kleine Person und sie haben den ersten Weg zu gehen"),
    ("he does the great day and he is the new way to make", "er macht den großen Tag und er ist der neue Weg zu machen"),
    ("i am the important year and i have the last time to go", "ich bin das wichtige Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is the last person and it makes the new way important", "es ist die letzte Person und es macht den neuen Weg wichtig"),
    ("you are the great thing and you have the last time to make", "du bist die große Sache und du hast die letzte Zeit zu machen"),
    ("the man has a great way and he makes the old thing go", "der Mann hat einen großen Weg und er macht die alte Sache gehen"),
    ("she is the new year and she has the last time to make", "sie ist das neue Jahr und sie hat die letzte Zeit zu machen"),
    ("we have an old way and we make the great day new", "wir haben einen alten Weg und wir machen den großen Tag neu"),
    ("they make a good person and they have the first time to go", "sie machen eine gute Person und sie haben die erste Zeit zu gehen"),
    ("he does the little year and he is the new way to make", "er macht das kleine Jahr und er ist der neue Weg zu machen"),
    ("i am the first way and i have the last time to go", "ich bin der erste Weg und ich habe die letzte Zeit zu gehen"),
    ("it is a great time and it makes the new thing important", "es ist eine große Zeit und es macht die neue Sache wichtig"),
    ("you are the old person and you have the last time to make", "du bist die alte Person und du hast die letzte Zeit zu machen"),
    ("the person has the important thing and she makes the old way go", "die Person hat die wichtige Sache und sie macht den alten Weg gehen"),
    ("she is a little year and she has the great day to make", "sie ist ein kleine Jahr und sie hat den großen Tag zu machen"),
    ("we have the last thing and we make the first way new", "wir haben die letzte Sache und wir machen den ersten Weg neu"),
    ("they make a new person and they have the last time to go", "sie machen eine neue Person und sie haben die letzte Zeit zu gehen"),
    ("he does the good way and he is the new year to make", "er macht den guten Weg und er ist das neue Jahr zu machen"),
    ("i am the great thing and i have the last time to go", "ich bin die große Sache und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the new thing important", "es ist der kleine Weg und es macht die neue Sache wichtig"),
    ("you are the new year and you have the last time to make", "du bist das neue Jahr und du hast die letzte Zeit zu machen"),
    ("the man has the little way and he makes the old thing go", "der Mann hat den kleinen Weg und er macht die alte Sache gehen"),
    ("she is the last way and she has the great day to make", "sie ist der letzte Weg und sie hat den großen Tag zu machen"),
    ("we have the good thing and we make the last time new", "wir haben die gute Sache und wir machen die letzte Zeit neu"),
    ("they make a new way and they have the first time to go", "sie machen einen neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great person and he is the new way to make", "er macht die große Person und er ist der neue Weg zu machen"),
    ("i am the little year and i have the last time to go", "ich bin das kleine Jahr und ich habe die letzte Zeit zu gehen"),
    ("it is the important way and it makes the new thing important", "es ist der wichtige Weg und es macht die neue Sache wichtig"),
    ("you are the new way and you have the last time to make", "du bist der neue Weg und du hast die letzte Zeit zu machen"),
    ("the person has the old person and she makes the new way go", "die Person hat die alte Person und sie macht den neuen Weg gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have a little year and we make the last thing new", "wir haben ein kleine Jahr und wir machen die letzte Sache neu"),
    ("they make the last person and they have the first way to go", "sie machen die letzte Person und sie haben den ersten Weg zu gehen"),
    ("he does the new way and he is the great way to make", "er macht den neuen Weg und er ist der große Weg zu machen"),
    ("i am the little person and i have the last time to go", "ich bin die kleine Person und ich habe die letzte Zeit zu gehen"),
    ("it is the great way and it makes the new thing important", "es ist der große Weg und es macht die neue Sache wichtig"),
    ("you are the new way and you have the last time to make", "du bist der neue Weg und du hast die letzte Zeit zu machen"),
    ("the man has the great way and he makes the old thing go", "der Mann hat den großen Weg und er macht die alte Sache gehen"),
    ("she is the new way and she has the last year to make", "sie ist der neue Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the great way and they have the first time to go", "sie machen den großen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the new way to make", "er macht den kleinen Weg und er ist der neue Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the new way and she makes the old thing go", "die Person hat den neuen Weg und sie macht die alte Sache gehen"),
    ("she is the little way and she has the great day to make", "sie ist der kleine Weg und sie hat den großen Tag zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the little way and it makes the great thing important", "es ist der kleine Weg und es macht die große Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the man has the new way and he makes the old thing go", "der Mann hat den neuen Weg und er macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the little way and we make the last thing new", "wir haben den kleinen Weg und wir machen die letzte Sache neu"),
    ("they make the new way and they have the first time to go", "sie machen den neuen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the little way and he is the great way to make", "er macht den kleinen Weg und er ist der große Weg zu machen"),
    ("i am the great way and i have the last time to go", "ich bin der große Weg und ich habe die letzte Zeit zu gehen"),
    ("it is the new way and it makes the little thing important", "es ist der neue Weg und es macht die kleine Sache wichtig"),
    ("you are the great way and you have the last time to make", "du bist der große Weg und du hast die letzte Zeit zu machen"),
    ("the person has the little way and she makes the old thing go", "die Person hat den kleinen Weg und sie macht die alte Sache gehen"),
    ("she is the great way and she has the last year to make", "sie ist der große Weg und sie hat das letzte Jahr zu machen"),
    ("we have the new way and we make the last thing new", "wir haben den neuen Weg und wir machen die letzte Sache neu"),
    ("they make the little way and they have the first time to go", "sie machen den kleinen Weg und sie haben die erste Zeit zu gehen"),
    ("he does the great way and he is the new way to make", "er macht den großen Weg und er ist der neue Weg zu machen"),
    ("i am the new way and i have the last time to go", "ich bin der neue Weg und ich habe die letzte Zeit zu gehen"),
]

sentence_pairs = sorted(list(set(sentence_pairs)))
#print(sentence_pairs)

np.random.seed(42)

validation_sentences = []
validation_indices = np.random.default_rng(42).choice(len(sentence_pairs), size=100, replace=False)
validation_indices = reversed(sorted(validation_indices))
for i in validation_indices:
    validation_sentences.append(sentence_pairs[i])
    del sentence_pairs[i]

validation_sentences = [(sentence[0] + ' ', sentence[1] + ' ') for sentence in validation_sentences]

#validation_sentences = []

most_used_english_words = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her",
    "she", "or", "an", "will", "my", "one", "all", "would", "there",
    "their", "what", "so", "up", "out", "if", "about", "who", "get",
    "which", "go", "me", "when", "make", "can", "like", "time", "no",
    "just", "him", "know", "take", "people", "into", "year", "your",
    "good", "some", "could", "them", "see", "other", "than", "then",
    "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well",
    "way", "even", "new", "want", "because", "any", "these", "give",
    "day", "most", "us", "is", "are", "was", "were", "been", "being",
    "have", "has", "had", "having", "do", "does", "did", "doing", "a",
    "an", "the", "and", "but", "if", "or", "because", "as", "until",
    "while", "of", "at", "by", "for", "with", "about", "against", "between",
    "into", "through", "during", "before", "after", "above", "below",
    "to", "from", "up", "down", "in", "out", "on", "off", "over",
    "under", "again", "further", "then", "once", "here", "there",
    "when", "where", "why", "how", "all", "any", "both", "each",
    "few", "more", "most", "other", "some", "such", "no", "nor",
    "not", "only", "own", "same", "so", "than", "too", "very",
    "s", "t", "can", "will", "just", "don", "should", "now",
    "d", "ll", "m", "o", "re", "ve", "y", "ain", "aren", "couldn",
    "didn", "doesn", "hadn", "hasn", "haven", "isn", "ma", "mightn",
    "mustn", "needn", "shan", "shouldn", "wasn", "weren", "won", "wouldn"
]

most_used_english_words = list(set(most_used_english_words))

dataset = open('/home/user/Desktop/datasets/deu.txt', 'r').readlines()
splitter = '	'
dataset = [j.split(splitter)[:2] for j in dataset]
#print(dataset[:100])

def preprocess_anki():
    dataset = open('/home/user/Desktop/datasets/deu.txt', 'r').readlines()
    splitter = '	'
    dataset = [j.split(splitter)[:2] for j in dataset]
    data_train = []
    mxlen = 0
    all_tokens = {}
    for sample in dataset:
        en = []
        de = []
        now = ''
        for j in sample[0]:
            if j in special_chars:
                if now != '':
                    en.append(now)
                    now = ''
                en.append(j)
            else:
                now += j.lower()
        if now != '':
            en.append(now)
            now = ''
        for j in sample[1]:
            if j in special_chars:
                if now != '':
                    de.append(now)
                    now = ''
                de.append(j)
            else:
                now += j.lower()
        if now != '':
            de.append(now)
            now = ''
        check = 0
        for j in en:
            if not j in (special_chars + most_used_english_words):
                check = 1
        if check or len(en) < 15:
            continue
        for j in en:
            all_tokens[j] = 1
        for j in de:
            all_tokens[j] = 1
        data_train.append([de, en])
        mxlen = max([mxlen, len(en) + 5, len(de) + 5])

    with open('./all_tokens.txt', 'w') as f:
        for i in all_tokens:
            f.write(i + '\n')
    with open('./mxlen.txt', 'w') as f:
        f.write(str(mxlen))
    all_tokens_list = open('./all_tokens.txt', 'r').readlines()
    all_tokens_list = [token[:-1] for token in all_tokens_list]
    all_tokens_list = sorted(all_tokens_list)
    for i in range(len(all_tokens_list)):
        all_tokens[all_tokens_list[i]] = i

    for i in range(len(data_train)):
        for j in range(len(data_train[i][1])):
            data_train[i][1][j] = [1, all_tokens[data_train[i][1][j]] / (len(all_tokens) + 1)]
        for j in range(len(data_train[i][0])):
            data_train[i][0][j] = all_tokens[data_train[i][0][j]]

    X = []
    Y = []
    for i in range(len(data_train)):
        X.append(data_train[i][1])
        Y.append(data_train[i][0])
    for i in range(len(X)):
        nowlen = len(X[i])
        for j in range(mxlen - nowlen):
            X[i].append([1, len(all_tokens) / (len(all_tokens) + 1)])
        for j in range(mxlen):
            X[i][j][0] = j / mxlen
        nowlen = len(Y[i])
        for j in range(mxlen - nowlen):
            Y[i].append(len(all_tokens))
    X = np.array(X, dtype='float32')
    Y = np.array(Y, dtype='float32')
    print(len(X))
    np.save('/home/user/Desktop/datasets/translation_en_de_anki_x.npy', X)
    np.save('/home/user/Desktop/datasets/translation_en_de_anki_y.npy', Y)

#preprocess_anki()
#sentence_pairs += validation_sentences[:3] * 100

#print('len', len(sentence_pairs))
tokens_en = {}
for i in sentence_pairs:
    #tokens_en[i[0]] = 1
    for j in i[0].split(' '):
        tokens_en[j] = 1
    for j in i[1].split(' '):
        tokens_en[j] = 1
#for key in tokens_en:
    #print(key)
print('tokens_en', len(tokens_en))

for i in range(len(sentence_pairs)):
    res = list(sentence_pairs[i])
    sentence_pairs[i] = (res[0] + ' ', res[1] + ' ')
    continue
    sentence_pairs[i] = list(sentence_pairs[i])
    sentence_pairs[i][0] = '$ ' + sentence_pairs[i][0] + ' $'
    sentence_pairs[i][1] = '$ ' + sentence_pairs[i][1] + ' $'
#for i in range(len(validation_sentences)):
    res = list(validation_sentences[i])
    if len(res[0].split(' ')) == 0:
        validation_sentences[i] = (res[0] + ' ' + res[0] + ' ' + res[0] + ' ', res[1] + ' ' + res[1] + ' ' + res[1] + ' ')
    else:
        validation_sentences[i] = (res[0] + ' ', res[1] + ' ')